.TH "explosive-c4" 6 "Feb 20, 2022" "Four in a row game"
.SH "NAME"
explosive-c4 \(em Implementation of four in a row game.
.SH "SYNOPSIS"
.PP
\fBexplosive-c4\fR

.SH "DESCRIPTION"
.PP
This is a four in a row game implementation.
.br

Players place their red or yellow pieces in a vertical board, where they fall down.
.br

The goal is to place four pieces of the same colour in a row. Horizontally, vertically or diagonally.
.br

It is possible to play against the computer or against another person.

.SH "REPORTING BUGS"
.PP
Report all bugs here: <https://github.com/ltworf/explosive-c4>

.SH "AUTHOR"
.PP
Written by Salvo "LtWorf" Tomaselli

.SH "COPYRIGHT"
.PP
Copyright © 2022 Salvo "LtWorf" Tomaselli. License AGPLv3: GNU Affero GPL version 3 <https://gnu.org/licenses/agpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
