name: Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y debhelper-compat build-essential qmake6 qt6-base-dev
    - name: qmake
      run: mkdir b; cd b; qmake6 ../src
    - name: compile
      run: cd b; make -j
